// constants/sections.js
export const NYT_SECTIONS = [
  { section: "home", title: "HOME" },
  { section: "arts", title: "ARTS" },
  { section: "automobiles", title: "AUTOMOBILES" },
  { section: "books", title: "BOOKS" },
  { section: "business", title: "BUSINESS" },
  { section: "fashion", title: "FASHION" },
  { section: "food", title: "FOOD" },
  { section: "health", title: "HEALTH" },
  { section: "insider", title: "INSIDER" },
  { section: "magazine", title: "MAGAZINE" },
  { section: "movies", title: "MOVIES" },
  { section: "nyregion", title: "NY REGION" },
  { section: "obituaries", title: "OBITUARIES" },
  { section: "opinion", title: "OPINION" },
  { section: "politics", title: "POLITICS" },
  { section: "realestate", title: "REAL ESTATE" },
  { section: "science", title: "SCIENCE" },
  { section: "sports", title: "SPORTS" },
  { section: "sundayreview", title: "SUNDAY REVIEW" },
  { section: "technology", title: "TECHNOLOGY" },
  { section: "theater", title: "THEATER" },
  { section: "t-magazine", title: "T MAGAZINE" },
  { section: "travel", title: "TRAVEL" },
  { section: "upshot", title: "UPSHOT" },
  { section: "us", title: "US" },
  { section: "world", title: "WORLD" },
];
